version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    working_directory: ~/repo

    steps:
      - run: sudo apt-get install -y libfuse2
      - run:
          name: Install latest yarn
          command: |
            curl -sS http://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - ;
            echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list ;
            sudo apt-get update && sudo apt-get install yarn
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
